const admin = require("firebase-admin");

if (!admin.apps.length) {
  const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_KEY);
  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
  });
}
const db = admin.firestore();

const PRODUCTS = [
  {
    id: "merch-white-sweater",
    name: "White Sweater",
    slug: "white-sweater",
    description: "Premium cotton blend sweater with ETFC embroidered logo",
    images: ["images/merch-white-sweater.png"],
    basePrice: 3499,
    offerPrice: 1999,
    offerEndsAt: admin.firestore.Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
    colors: ["White", "Black", "Grey"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Apparel",
    stock: 50,
    active: true,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: "merch-white-full",
    name: "White Full Set",
    slug: "white-full-set",
    description: "Complete white outfit: hoodie, tee, and shorts with ETFC branding",
    images: ["images/merch-white-full.png"],
    basePrice: 5999,
    offerPrice: 3499,
    offerEndsAt: admin.firestore.Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
    colors: ["White"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Sets",
    stock: 30,
    active: true,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: "merch-sleeve-hoodie-tshirt-shorts",
    name: "Sleeve Hoodie + Tee + Shorts Set",
    slug: "sleeve-hoodie-tshirt-shorts-set",
    description: "3-piece set: long-sleeve hoodie, matching tee, and fight shorts",
    images: ["images/merch-sleeve-hoodie-tshirt-shorts.png"],
    basePrice: 6499,
    offerPrice: 3999,
    offerEndsAt: admin.firestore.Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
    colors: ["Black/Red", "Navy/Gold", "Grey/Black"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Sets",
    stock: 25,
    active: true,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: "merch-shorts",
    name: "Fight Shorts",
    slug: "fight-shorts",
    description: "MMA-cut performance shorts with ETFC logo patch",
    images: ["images/merch-shorts.png"],
    basePrice: 2299,
    offerPrice: 1299,
    offerEndsAt: admin.firestore.Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
    colors: ["Black", "Navy", "Red"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Apparel",
    stock: 60,
    active: true,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: "merch-open-sleeve-jacket",
    name: "Open Sleeve Jacket",
    slug: "open-sleeve-jacket",
    description: "Lightweight varsity-style jacket with open sleeves and ETFC patches",
    images: ["images/merch-open-sleeve-jacket.png"],
    basePrice: 4499,
    offerPrice: 2699,
    offerEndsAt: admin.firestore.Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
    colors: ["Black/Red", "Navy/Gold"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Outerwear",
    stock: 35,
    active: true,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: "merch-bracelet",
    name: "ETFC Bracelet",
    slug: "etfc-bracelet",
    description: "Silicone fight bracelet with debossed ETFC logo — 2 pack",
    images: ["images/merch-bracelet.png"],
    basePrice: 499,
    offerPrice: 249,
    offerEndsAt: admin.firestore.Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
    colors: ["Black/Red", "White/Gold", "Black/Gold"],
    sizes: ["One Size"],
    category: "Accessories",
    stock: 100,
    active: true,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: "merch-boxing-gwan",
    name: "Boxing Gwan",
    slug: "boxing-gwan",
    description: "Traditional Ethiopian boxing hand wraps (gwan) with ETFC branding",
    images: ["images/merch-boxing-gwan.png"],
    basePrice: 899,
    offerPrice: 499,
    offerEndsAt: admin.firestore.Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
    colors: ["Red", "Black", "White"],
    sizes: ["One Size"],
    category: "Accessories",
    stock: 80,
    active: true,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: "merch-boxing-glove",
    name: "Boxing Gloves",
    slug: "boxing-gloves",
    description: "Pro training gloves — genuine leather, 14oz, ETFC branded",
    images: ["images/merch-boxing-glove.png"],
    basePrice: 4999,
    offerPrice: 2999,
    offerEndsAt: admin.firestore.Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
    colors: ["Red/Black", "Black/Gold"],
    sizes: ["12oz", "14oz", "16oz"],
    category: "Gear",
    stock: 20,
    active: true,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: "merch-blue-full",
    name: "Blue Full Set",
    slug: "blue-full-set",
    description: "Complete blue outfit: hoodie, tee, and shorts with ETFC branding",
    images: ["images/merch-blue-full.png"],
    basePrice: 5999,
    offerPrice: 3499,
    offerEndsAt: admin.firestore.Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
    colors: ["Royal Blue"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Sets",
    stock: 30,
    active: true,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: "merch-blue-tshirt",
    name: "Blue T-Shirt",
    slug: "blue-tshirt",
    description: "Classic blue cotton tee with ETFC Fight Night chest print",
    images: ["images/merch-blue-tshirt.png"],
    basePrice: 1899,
    offerPrice: 999,
    offerEndsAt: admin.firestore.Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
    colors: ["Royal Blue", "Navy", "Light Blue"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Apparel",
    stock: 70,
    active: true,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: "merch-black-full",
    name: "Black Full Set",
    slug: "black-full-set",
    description: "Complete black outfit: hoodie, tee, and shorts with gold ETFC branding",
    images: ["images/merch-black-full.png"],
    basePrice: 6499,
    offerPrice: 3799,
    offerEndsAt: admin.firestore.Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)),
    colors: ["Black"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    category: "Sets",
    stock: 25,
    active: true,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
  },
];

async function seed() {
  const batch = db.batch();
  
  for (const product of PRODUCTS) {
    const ref = db.collection("merchProducts").doc(product.id);
    batch.set(ref, product);
    console.log(`Queued: ${product.name}`);
  }
  
  await batch.commit();
  console.log("✅ All 11 products seeded!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});